### ISSUE TITLE
model with name "Class" in prisma.schema failes

### ISSUE THREAD

**Issue by premkumar5012002** [MichalLytek/typegraphql-prisma#127]
**Describe the Bug**
When try to create type "Class" in prisma.schema file. it failes bacause of the deserved name for Class in javascript

**To Reproduce**

prisma.schema file

Type Class{
  name  String @id
}

**Expected Behavior**

**Logs**
school_companion/src/generated/typegraphql-prisma/resolvers/relations/Class/ClassRelationsResolver.js:65
 > {
 ^

SyntaxError: Unexpected token '>'
    at Object.compileFunction (node:vm:353:18)
    at wrapSafe (node:internal/modules/cjs/loader:1039:15)
    at Module._compile (node:internal/modules/cjs/loader:1073:27)
    at Module._compile (/Users/prem/Projects/school_companion/node_modules/source-map-support/source-map-support.js:547:25)
    at Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.nodeDevHook [as .js] (/Users/prem/Projects/school_companion/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
[ERROR] 21:47:13 SyntaxError: Unexpected token '>'

**Environment (please complete the following information):**

- OS: [Mac os]
- Node (e.g. 16.2.0)
- `typegraphql-prisma` version [e.g. 0.14.4] (please check if the bug still exist in newest release)
- Prisma 2 version [e.g. 2.18.0]
- TypeScript version (e.g. 4.2.2)

**Additional Context**

**Comment by MichalLytek** [comment]
Use type rename feature:
https://github.com/MichalLytek/typegraphql-prisma#changing-exposed-model-type-name
