### ISSUE TITLE
Compilation Problem

### ISSUE THREAD

**Issue by blepe** [MichalLytek/typegraphql-prisma#140]
**Describe the Bug**
When running the example from typegraphql-prisma/examples/1-prototyping/ I get the following Error:

```
/app/node_modules/type-graphql/dist/helpers/findType.js:19,
        throw new errors_1.NoExplicitTypeError(prototype.constructor.name, propertyKey, parameterIndex, argName);,
              ^,
Error: Unable to infer GraphQL type from TypeScript reflection system. You need to provide explicit type for parameter #2 of 'post' of 'PostCrudResolver' class.,
```

**To Reproduce**
Copy the code in Docker Image node:lts-buster or node:12-buster...
npm i
npx migrate dev --name foobar
npm start

**Expected Behavior**
Example runs without error...

**Logs**
```
Error: Unable to infer GraphQL type from TypeScript reflection system. You need to provide explicit type for parameter #2 of 'post' of 'PostCrudResolver' class.,
    at Object.findType (/app/node_modules/type-graphql/dist/helpers/findType.js:19:15),
    at Object.getParamInfo (/app/node_modules/type-graphql/dist/helpers/params.js:10:49),
    at /app/node_modules/type-graphql/dist/decorators/Args.js:12:25,
    at /app/prisma/generated/type-graphql/resolvers/crud/Post/PostCrudResolver.ts:28:37,
    at DecorateProperty (/app/node_modules/reflect-metadata/Reflect.js:553:33),
    at Object.decorate (/app/node_modules/reflect-metadata/Reflect.js:123:24),
    at __decorate (/app/prisma/generated/type-graphql/resolvers/crud/Post/PostCrudResolver.ts:16:92),
    at Object.<anonymous> (/app/prisma/generated/type-graphql/resolvers/crud/Post/PostCrudResolver.ts:26:3),
    at Module._compile (internal/modules/cjs/loader.js:999:30),
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1295:23),
```

**Environment (please complete the following information):**

- OS: Docker on Raspberry Pi OS 64bit
- Node (LTS-Buster or 12-Buster from Docker)

```
  "dependencies": {
    "@prisma/client": "~2.26.0",
    "@types/graphql-fields": "^1.3.3",
    "apollo-server": "^2.25.2",
    "graphql": "^15.5.1",
    "graphql-fields": "^2.0.3",
    "graphql-scalars": "^1.10.0",
    "reflect-metadata": "^0.1.13",
    "type-graphql": "^1.1.1"
  },
  "devDependencies": {
    "@types/node": "^15.12.5",
    "prisma": "~2.26.0",
    "ts-node": "^10.0.0",
    "typegraphql-prisma": "0.14.5",
    "typescript": "^4.3.4"
  }
```

**Additional Context**

**Comment by MichalLytek** [comment]
The example works ok when you run in on your local node by cloning git repository.

You need to make sure you properly compile the app when you build a docker image.
I don't see your dockerfile nor prisma schema, so can't help with that.

See https://github.com/MichalLytek/typegraphql-prisma/discussions/128

**Comment by blepe** [comment]
I'll prepare an example... BRB

**Comment by blepe** [comment]
First of all, Thanks for your help!

Example Dockerfile available at https://github.com/blepe/typegraphql-prisma-docker
Dockerbuild (for linux/arm64) available at https://hub.docker.com/repository/docker/blepe/typegraphql-prisma-docker

Running the Docker image results in:

```
,
> @ start /app,
> ts-node --transpile-only ./index.ts,
,
,
/app/node_modules/type-graphql/dist/helpers/findType.js:19,
        throw new errors_1.NoExplicitTypeError(prototype.constructor.name, propertyKey, parameterIndex, argName);,
              ^,
Error: Unable to infer GraphQL type from TypeScript reflection system. You need to provide explicit type for parameter #2 of 'post' of 'PostCrudResolver' class.,
    at Object.findType (/app/node_modules/type-graphql/dist/helpers/findType.js:19:15),
    at Object.getParamInfo (/app/node_modules/type-graphql/dist/helpers/params.js:10:49),
    at /app/node_modules/type-graphql/dist/decorators/Args.js:12:25,
    at /app/prisma/generated/type-graphql/resolvers/crud/Post/PostCrudResolver.ts:28:37,
    at DecorateProperty (/app/node_modules/reflect-metadata/Reflect.js:553:33),
    at Object.decorate (/app/node_modules/reflect-metadata/Reflect.js:123:24),
    at __decorate (/app/prisma/generated/type-graphql/resolvers/crud/Post/PostCrudResolver.ts:16:92),
    at Object.<anonymous> (/app/prisma/generated/type-graphql/resolvers/crud/Post/PostCrudResolver.ts:26:3),
    at Module._compile (internal/modules/cjs/loader.js:1085:14),
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1295:23),
npm ERR! code ELIFECYCLE,
npm ERR! errno 1,
npm ERR! @ start: `ts-node --transpile-only ./index.ts`,
npm ERR! Exit status 1,,
 ,
npm ERR! Failed at the @ start script.,
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.,
,
npm ERR! A complete log of this run can be found in:,
npm ERR!     /root/.npm/_logs/2021-07-21T13_52_16_407Z-debug.log
```

Compilation Problem might not be the right description...

**Comment by MichalLytek** [comment]
Have you set your `tsconfig.json` properly? Have you ever used TypeGraphQL?

**Comment by blepe** [comment]
I've never used TypeGraphQL before...

Well, there was no tsconfig.json in the example so I didn't add one... sry.. I'm an absolute beginner in the Typescript World :)... 
My "real" dev-testing-project-thing is running now after I added the proper tsconfig.json...  I'll update the GitHub
and Dockerhub projects from this ticket... :) Thank you very much!!!

**Comment by MichalLytek** [comment]
https://typegraphql.com/docs/installation.html

**Comment by blepe** [comment]
It works like a charm now! thank you so much! This project is really great!
