### ISSUE TITLE
Error: Cannot find module '../../package.json'

### ISSUE THREAD

**Issue by PHILLIPS71** [MichalLytek/typegraphql-prisma#16]
After updating to version v0.8.1 I'm getting errors when trying to generate the graphql types. Looks that the path to the package.json path is incorrect.  

![Capture](https://user-images.githubusercontent.com/6015550/95817326-dcfb0700-0d6c-11eb-8cd3-f1d4ad9e94e5.PNG)

**Comment by JohannesKlauss** [comment]
Same here.
Error output:
```
Error: Cannot find module '../../package.json'
Require stack:
- /Users/johannesklauss/Documents/Development/Syra/node_modules/typegraphql-prisma/utils/prisma-version.js
- /Users/johannesklauss/Documents/Development/Syra/node_modules/typegraphql-prisma/generator/generate-code.js
- /Users/johannesklauss/Documents/Development/Syra/node_modules/typegraphql-prisma/cli/prisma-generator.js
- /Users/johannesklauss/Documents/Development/Syra/node_modules/typegraphql-prisma/cli/generator.js
- /Users/johannesklauss/Documents/Development/Syra/node_modules/typegraphql-prisma/generator.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at getPeerDependencyPrismaRequirement (/Users/johannesklauss/Documents/Development/Syra/node_modules/typegraphql-prisma/utils/prisma-version.js:12:28)
    at Object.ensureInstalledCorrectPrismaPackage (/Users/johannesklauss/Documents/Development/Syra/node_modules/typegraphql-prisma/utils/prisma-version.js:18:32)
    at Object.generateCode [as default] (/Users/johannesklauss/Documents/Development/Syra/node_modules/typegraphql-prisma/generator/generate-code.js:26:22)
    at Object.generate [as onGenerate] (/Users/johannesklauss/Documents/Development/Syra/node_modules/typegraphql-prisma/cli/prisma-generator.js:32:34)
```

Doesn't happen with `0.8.0`

**Comment by MichalLytek** [comment]
Please try with 0.8.2 😉
