### ISSUE TITLE
"RangeError: Maximum call stack size exceeded" running server

### ISSUE THREAD

**Issue by cgodkin** [MichalLytek/typegraphql-prisma#246]
**Describe the Bug**
We have a large schema with 80 models created by introspecting a SQL Server database.
The generate step works fine, but the server (a copy of the "Prototyping" example's server) exits with "RangeError: Maximum call statck size exceeded."

**To Reproduce**
Use this repo: https://github.com/cgodkin/typegraphql-prisma-problem 
This is essentially https://github.com/MichalLytek/typegraphql-prisma/tree/main/examples/1-prototyping with updated dependencies and our schema.  Then do this:
```
yarn
yarn generate
yarn start
```

**Expected Behavior**
What should happen is a database connection error since you won't have the database configured.  Something like this:
```
yarn run v1.22.17
$ ts-node --transpile-only ./index.ts
PrismaClientInitializationError: Error creating a database connection. (Error creating a database connection.)
    at d:\users\carl\typegraphql-prisma-problem\node_modules\@prisma\client\runtime\index.js:26873:22 {
  clientVersion: '3.2.1',
  errorCode: undefined
}
Done in 5.75s.
```
Instead, you will get `RangeError: Maximum call stack size exceeded`

**Logs**
```
yarn run v1.22.17
$ ts-node --transpile-only ./index.ts
d:\users\carl\typegraphql-prisma-problem\node_modules\typescript\lib\typescript.js:41955
        var preDirectoryResolutionCache = createPerDirectoryResolutionCache(currentDirectory, getCanonicalFileName, directoryToModuleNameMap || (directoryToModuleNameMap = createCacheWithRedirects(options)));
                                          ^
RangeError: Maximum call stack size exceeded
    at Object.createModuleResolutionCache (d:\users\carl\typegraphql-prisma-problem\node_modules\typescript\lib\typescript.js:41955:43)
    at Object.createProgram (d:\users\carl\typegraphql-prisma-problem\node_modules\typescript\lib\typescript.js:113808:40)
    at Object.transpileModule (d:\users\carl\typegraphql-prisma-problem\node_modules\typescript\lib\typescript.js:141719:26)
    at d:\users\carl\typegraphql-prisma-problem\node_modules\ts-node\src\index.ts:1204:21
    at Object.compile (d:\users\carl\typegraphql-prisma-problem\node_modules\ts-node\src\index.ts:1243:30)
    at Module.m._compile (d:\users\carl\typegraphql-prisma-problem\node_modules\ts-node\src\index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (d:\users\carl\typegraphql-prisma-problem\node_modules\ts-node\src\index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
error Command failed with exit code 1.
```

**Environment (please complete the following information):**

- OS: [e.g. Windows 10 21H1]
- Node: v16.13.2
- `typegraphql-prisma` version [e.g. 0.11.1]: 0.18.4
- Prisma version [e.g. 2.18.0]: 3.8.0
- TypeScript version (e.g. 4.2.2): 4.4.4

**Additional Context**
This seems like #212 (closed as a dup, but happened during generate) and #202 (still open).  We have tried various things suggested in the latter but nothing has helped.   Thanks!

**Comment by MichalLytek** [comment]
The problem comes from `ts-node`. Maybe you can try to run the server without type-checking on the fly.

**Comment by cgodkin** [comment]
Thanks for the quick response, though I don't think I understand what you are asking.

Isn't running `ts-node` with `--transpile-only`  not doing type checking?  Just transpiling?   

I'm eager to try whatever you suggest but perhaps you could suggest the options or configuration changes that you mean?  Thanks.

**Comment by MichalLytek** [comment]
Yes, maybe the codebase is too big to check all the types but you can just run in transpile only mode, so it won't break of call stack size or other OOM error.

**Comment by cgodkin** [comment]
Hi again.  I am sorry, but I do not understand your recommendation.  I think I _am_ running in transpile-only mode:
```
    "start": "ts-node --transpile-only ./index.ts",
```
What change are you suggesting?   Thanks very much.

I also updated my [test project](https://github.com/cgodkin/typegraphql-prisma-problem) to the latest `prisma`, `@prisma/client`, and `typegraphql-prisma` just to check if that helped but I get "Maximum call size exceeded."

**Comment by MichalLytek** [comment]
I haven't seen that `--transpile-only`, sorry.

I don't have a solution for such large schemas.

**Comment by cgodkin** [comment]
Thanks for the reply.  It's not really that large, is it?  The schema.prisma file has 80 `model`s and it's 1354 lines long.  

Someone made a comment [here](https://github.com/MichalLytek/typegraphql-prisma/issues/10) that they have

> a prisma model made by introspection for about 122 tables and has 1650 lines

 and they got it to work.  I'm happy to try any ideas you or anyone has!  Thanks again.

**Comment by alexkharech** [comment]
+1

**Comment by Maloc** [comment]
Is there any progress on this issue? I saw in the [comment](https://github.com/MichalLytek/typegraphql-prisma/issues/13#issuecomment-707079005) that an option could be set up to emit all generated files in a single file, wouldn't that be the solution to avoid circular dependencies and thus maximum call stack?
