### ISSUE TITLE
Cannot filter null json columns

### ISSUE THREAD

**Issue by mdesousa** [MichalLytek/typegraphql-prisma#321]
You cannot filter records where a json column is null

**To Reproduce**
define a json column in the prisma schema like this:
```prisma
model MyTable {
  id String @id @db.Uuid
  myColumn Json?
}
```
then build graphql schema, insert a few rows and execute the following query
```graphql
query {
  myTables (where: { myColumn: { equals: null }}) {
    id
    myColumn
  }
}```

**Expected Behavior**
The query should return all rows where myColumn is null

**Logs**
```
Argument equals for where.myColumns.equals must not be null. Please use undefined instead.

      at Document.validate (/app/node_modules/@prisma/client/runtime/index.js:27354:20)
      at serializationFn (/app/node_modules/@prisma/client/runtime/index.js:29815:19)
      at runInChildSpan (/app/node_modules/@prisma/client/runtime/index.js:23564:12)
      at PrismaClient._executeRequest (/app/node_modules/@prisma/client/runtime/index.js:29822:31)
      at consumer (/app/node_modules/@prisma/client/runtime/index.js:29751:23)
      at /app/node_modules/@prisma/client/runtime/index.js:29748:96
      at authz (/app/backend/src/common/prisma/middleware.ts:132:32)
      at /app/node_modules/@prisma/client/runtime/index.js:29748:22
      at runInChildSpan (/app/node_modules/@prisma/client/runtime/index.js:23564:12)
      at consumer (/app/node_modules/@prisma/client/runtime/index.js:29747:20)
      at /app/node_modules/@prisma/client/runtime/index.js:29756:51
      at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
      at /app/node_modules/@prisma/client/runtime/index.js:29756:29
      at runInChildSpan (/app/node_modules/@prisma/client/runtime/index.js:23564:12)
      at PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:29753:22)
      at requestFn (/app/node_modules/@prisma/client/runtime/index.js:28475:65)
      at /app/node_modules/@prisma/client/runtime/index.js:28488:18
      at _callback (/app/node_modules/@prisma/client/runtime/index.js:25994:52)
      at PrismaPromise.then (/app/node_modules/@prisma/client/runtime/index.js:26001:14)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    locations: [ [Object] ],
    path: [ 'myTables' ]
  }
]
[GraphQLError [Object]: 
Invalid `helpers_1.getPrismaFromContext)(ctx).myTable.findMany()` invocation in
/app/node_modules/@generated/type-graphql/resolvers/crud/myTable/myTableCrudResolver.js:68:66

   65 }
   66 async myTables(ctx, info, args) {
   67     const { _count } = (0, helpers_1.transformFields)((0, graphql_fields_1.default)(info));
→  68     return (0, helpers_1.getPrismaFromContext)(ctx).myTable.findMany({
            where: {
              myColumn: {
                equals: null
                        ~~~~
              }
            }
          })

Argument equals for where.myColumn.equals must not be null. Please use undefined instead.
```

**Environment**

- typegraphql-prisma@0.21.3
- prisma@4.2.1
- type-graphql@1.1.1

**Additional Context**
Seems related to #228 and #305. The old approach of using "DbNull" does not seem to work anymore.
Thanks

**Comment by MichalLytek** [comment]
Duplicate of #305 🔒
