### ISSUE TITLE
Getting error when running prisma generate on docker build command

### ISSUE THREAD

**Issue by thakkaryash94** [MichalLytek/typegraphql-prisma#33]
Thank you for the amazing library. When running prisma generate inside docker build command, I am getting below error. Though, prisma client is able to generate the code but not typegraphql-prisma.

```
> prisma generate


Prisma schema loaded from prisma/schema.prisma
Error:
TypeError: Cannot read property 'datamodel' of undefined
    at Object.generateCode [as default] (/home/app/node_modules/typegraphql-prisma/lib/generator/generate-code.js:37:29)
    at Object.generate [as onGenerate] (/home/app/node_modules/typegraphql-prisma/lib/cli/prisma-generator.js:32:34)
    at async LineStream.<anonymous> (/home/app/node_modules/@prisma/generator-helper/dist/generatorHandler.js:13:32)


✔ Generated Prisma Client (version: 2.11.0) to ./node_modules/@prisma/client in 277ms
```

Here is my Dockerfile.
```
FROM node:lts AS base

WORKDIR /home/app

COPY package*.json ./

RUN npm install

COPY src src
COPY prisma prisma
COPY tsconfig.json tsconfig.json

RUN npm run generate:prisma
```

Here is my schema.prisma file header.
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator typegraphql {
  provider           = "typegraphql-prisma"
  useOriginalMapping = true
}

generator client {
  provider = "prisma-client-js"
}
```

**Comment by thakkaryash94** [comment]
I check the node_modules source code, it looks like generateCode function is not getting `dmmf`. Here is the source code link. https://github.com/MichalLytek/typegraphql-prisma/blob/main/src/generator/generate-code.ts#L69

I don't have much experience prisma generator system, so need your help.

**Comment by thakkaryash94** [comment]
It looks like an issue from prisma side. The postinstall script fails but running manual `npx prisma generate` is working.
