### ISSUE TITLE
Failed to generate outputs

### ISSUE THREAD

**Issue by kaisheng1** [MichalLytek/typegraphql-prisma#91]
**The log after I run ```npx prisma generate```**
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: 
✔ Generated Prisma Client (2.20.1) to ./node_modules/@prisma/client in 173ms

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object
    at Object.mkdir (internal/fs/promises.js:467:10)
    at Object.generate [as onGenerate] (/home/tung/Documents/projects/typegraphql-prisma-demo/node_modules/typegraphql-prisma/lib/cli/prisma-generator.js:15:25)
    at LineStream.<anonymous> (/home/tung/Documents/projects/typegraphql-prisma-demo/node_modules/@prisma/generator-helper/dist/generatorHandler.js:13:46)
    at LineStream.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at LineStream.Readable.push (internal/streams/readable.js:223:10)
    at LineStream.Transform.push (internal/streams/transform.js:166:32)
    at LineStream._pushBuffer (/home/tung/Documents/projects/typegraphql-prisma-demo/node_modules/@prisma/generator-helper/dist/byline.js:108:23)
    at LineStream._transform (/home/tung/Documents/projects/typegraphql-prisma-demo/node_modules/@prisma/generator-helper/dist/byline.js:100:10)

**My node packages:** 
```
  "dependencies": {
    "@prisma/client": "^2.20.1",
    "class-validator": "^0.13.1",
    "graphql-fields": "^2.0.3",
    "graphql-scalars": "^1.9.0",
    "graphql-yoga": "^1.18.3",
    "reflect-metadata": "^0.1.13",
    "type-graphql": "^1.1.1"
  },
  "devDependencies": {
    "@types/graphql-fields": "^1.3.3",
    "@types/node": "^14.14.37",
    "@types/ws": "^7.4.0",
    "prisma": "^2.20.1",
    "ts-node": "^9.1.1",
    "ts-node-dev": "^1.1.6",
    "typegraphql-prisma": "^0.12.0",
    "typescript": "^4.2.3"
  }
```

**Comment by MichalLytek** [comment]
Are you using `SKIP_PRISMA_VERSION_CHECK` env variable? 

Because `typegraphql-prisma@0.12.0` is not compatible with Prisma `2.20.1`:
https://github.com/MichalLytek/typegraphql-prisma/blob/main/package.json#L20

and the error that would normally appear prevents from reporting such issues 🔒
