### ISSUE TITLE
Prisma 2.20 -- "path" argument must be of type string

### ISSUE THREAD

**Issue by tradical-allstripes** [MichalLytek/typegraphql-prisma#92]
**Describe the Bug**
After installing the newest Prisma version (2.20.1), I get an error saying the `path` argument needs to be a string.

I tried reinstalling and clearing `node_modules`, but the only thing that fixed it was reverting to prisma 2.19.

**To Reproduce**

```bash
npm i @prisma/client@2.20.1 prisma@2.20.1
npm i # runs prisma generate
```

**Expected Behavior**
Prisma generation should complete without error

**Logs**
```
✔ Generated Prisma Client (2.20.1) to ./node_modules/@prisma/client in 892ms

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object
    at Object.mkdir (node:internal/fs/promises:528:10)
    at Object.generate [as onGenerate] (/Users/tradical/src/allstripes/allstripes-app/api/node_modules/typegraphql-prisma/lib/cli/prisma-generator.js:15:25)
    at LineStream.<anonymous> (/Users/tradical/src/allstripes/allstripes-app/api/node_modules/@prisma/generator-helper/dist/generatorHandler.js:13:46)
    at LineStream.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at LineStream.Readable.push (node:internal/streams/readable:227:10)
    at LineStream._pushBuffer (/Users/tradical/src/allstripes/allstripes-app/api/node_modules/@prisma/generator-helper/dist/byline.js:108:23)
    at LineStream._transform (/Users/tradical/src/allstripes/allstripes-app/api/node_modules/@prisma/generator-helper/dist/byline.js:100:10)
    at LineStream.Transform._write (node:internal/streams/transform:184:23)
```
**Environment (please complete the following information):**

- OS: Mac OS 11.2.3
- Node: 15.12.0
- `typegraphql-prisma` version: 0.12.0
- Prisma 2 version 2.20.1
- TypeScript version: 4.2.2

**Additional Context**
 I did a little digging and it seems that, while creating the directory for the generated code, Prisma passes the output directory name wrapped in an object, while this plugin expected it to just be a string. My guess is that, in 2.20, Prisma changed the contract of this code.

**Comment by MichalLytek** [comment]
`typegraphql-prisma` is designed to work with a selected versions of prisma.
`v0.12.0` works with Prisma ~2.19.0.

Normally you would receive an error about Prisma version mismtach. However Prisma introduced breaking change in supplying data to generator, so it fails before the check happens.

Will be fixed in the next release. Leaving this open to prevent other reports.

**Comment by tradical-allstripes** [comment]
Thanks so much for the prompt reply! Sounds good to me.

**Comment by mohsinamjad** [comment]
having same issue on prisma-generate 
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:120:11)
```

**Comment by MichalLytek** [comment]
Just wait guys for the updated release. For now stay on `0.12.0` and Prisma `2.19`.

**Comment by MichalLytek** [comment]
Fixed by 76818e6, released in `v0.13.0 🚀

**Comment by nephix** [comment]
I'm having the same issue with `typegraphql-prisma@^0.13.1` and `prisma@~2.20.1`:

```
$ npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:121:11)
    at Object.join (path.js:1039:7)
    at getDotPrismaDir (XXXXXXX/packages/server/node_modules/@prisma/client/generator-build/index.js:72856:33)
    at Object.generateClient (XXXXXXX/packages/server/node_modules/@prisma/client/generator-build/index.js:72878:49)
    at Object.onGenerate (XXXXXXX/packages/server/node_modules/@prisma/client/generator-build/index.js:78167:34)
    at LineStream.<anonymous> (XXXXXXX/packages/server/node_modules/@prisma/client/generator-build/index.js:2802:40)
    at LineStream.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at LineStream.Readable.push (_stream_readable.js:218:10)


TypeError: Cannot destructure property 'datamodel' of 'undefined' as it is undefined.
    at new DmmfDocument (XXXXXXX/packages/server/node_modules/typegraphql-prisma/lib/generator/dmmf/dmmf-document.js:6:19)
    at Object.generateCode [as default] (XXXXXXX/packages/server/node_modules/typegraphql-prisma/lib/generator/generate-code.js:41:26)
    at Object.generate [as onGenerate] (XXXXXXX/packages/server/node_modules/typegraphql-prisma/lib/cli/prisma-generator.js:42:34)
    at async LineStream.<anonymous> (XXXXXXX/packages/server/node_modules/@prisma/generator-helper/dist/generatorHandler.js:13:32)

```

**Comment by lcanavesio** [comment]
Hi @MichalLytek 
In production mode i recive: graphql The "path" argument must be of type string or an instance of Buffer or URL. Received undefined.
What could be missing?  on localhost it works perfect for me

I use:
"type-graphql": "^1.1.1"
"typegraphql-nestjs": "^0.4.1"
"typegraphql-prisma": "^0.19.0"
"@prisma/client": "^3.9.2"
"@nestjs/core": "^8.2.3"

dev
"prisma": "^3.9.2"
